"""Render references.yaml as the numbered list on the References slide.

Writes references.tex (two-column, \\scriptsize) for \\input in slides.tex. The
numbers are the list order, the same numbers plot_costs.py prints in figure
labels and legends.
"""

import re
from pathlib import Path
from urllib.parse import urlparse

import yaml

HERE = Path(__file__).parent
if "snakemake" in globals():
    SRC, OUT, NUMS = Path(snakemake.input[0]), Path(snakemake.output.list), Path(snakemake.output.nums)
else:
    SRC, OUT, NUMS = HERE / "references.yaml", HERE / "references.tex", HERE / "refnums.tex"


def tex(s):
    return (s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")
            .replace("–", "--").replace("—", "---"))


refs = yaml.safe_load(SRC.read_text())
lines = [r"% generated by make_references.py from references.yaml -- do not edit",
         r"\begin{multicols}{2}\tiny\setlength{\parskip}{0.6pt}\raggedright"]
for i, r in enumerate(refs, 1):
    entry = tex(r["cite"])
    if r.get("url"):
        host = urlparse(r["url"]).netloc.removeprefix("www.")
        entry += r" \gray{\href{" + r["url"] + "}{" + tex(host) + "}}"
    lines.append(r"\noindent\hangindent=2.2em\hangafter=1\makebox[2.2em][l]{\textbf{[" + str(i) + "]}}"
                 + entry + r"\par")
lines.append(r"\end{multicols}")
OUT.write_text("\n".join(lines) + "\n")
# \ref<key> macros (key without hyphens) so slides.tex can cite by key, e.g. [\refpriam]
NUMS.write_text("% generated by make_references.py -- reference numbers by key\n" + "".join(
    f"\\newcommand{{\\ref{re.sub('[^a-z]', '', r['key'])}}}{{{i}}}\n" for i, r in enumerate(refs, 1)))
print(f"wrote {OUT}, {NUMS} ({len(refs)} references)")
