"""Hydrogen store, storage step: no cost-versus-deployment series exists, so the figure shows the
two cost levels the model can use as horizontal lines, in the style of the experience-curve
figures: the pressurised-tank option (the 2025 baseline, red dashed "model start") and the
salt-cavern option (grey dashed), both from the Danish Energy Agency storage catalogue as
carried in PyPSA/technology-data, converted to the base currency/year. Per kWh of hydrogen
(lower heating value) and, in the labels, per kWh of electricity out through the fuel cell.
Also writes h2-storage_sources.tex (clickable [n] sources for the slide).
Run standalone:  python plot_h2_storage.py
"""
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402
import yaml  # noqa: E402
from matplotlib.ticker import FuncFormatter, LogLocator, NullFormatter  # noqa: E402

from common import grid, make_to_base  # noqa: E402
from common import save as _save  # noqa: E402

if "snakemake" in globals():
    CFG = snakemake.config
    TD = Path(snakemake.input.td)
    COMPILED = Path(snakemake.input.compiled)
    OUTPUTS = [Path(p) for p in snakemake.output]
else:
    _HERE = Path(__file__).resolve().parent
    CFG = yaml.safe_load((_HERE / "config.yaml").read_text())
    TD = _HERE / "data" / "technology-data" / f"costs_2025_{CFG['technology_data']['tag']}.csv"
    COMPILED = _HERE / "build" / "costs_2025_compiled.csv"
    OUTPUTS = [_HERE / "figures" / "learning" / f"h2-storage.{fmt}" for fmt in CFG["plotting"]["formats"]]
    OUTPUTS.append(_HERE / "figures" / "learning" / "h2-storage_sources.tex")
OUTPUTS[0].parent.mkdir(parents=True, exist_ok=True)

BASE = f"{CFG['base_currency']}{CFG['base_currency_year']}"
to_base = make_to_base(CFG)
DEA_URL = "https://ens.dk/en/analyses-and-statistics/technology-data-energy-storage"
TD_URL = f"https://github.com/PyPSA/technology-data/blob/{CFG['technology_data']['tag']}/outputs/costs_2025.csv"

td = pd.read_csv(TD)
OPTIONS = [  # technology-data key, short label, DEA sheet, style
    ("hydrogen storage tank type 1 including compressor", "pressurised tank incl. compressor", "151a", "tank"),
    ("hydrogen storage underground", "salt cavern", "151c", "cavern"),
]
rows = {}
for key, label, sheet, kind in OPTIONS:
    r = td[(td["technology"] == key) & (td["parameter"] == "investment")].iloc[0]
    assert r["unit"].startswith("EUR/kWh"), r["unit"]
    rows[kind] = {"label": label, "sheet": sheet, "eur": float(r["value"]), "year": int(r["currency_year"]),
                  "usd": float(to_base(float(r["value"]), "EUR", int(r["currency_year"]))[0])}
comp = pd.read_csv(COMPILED)
eff = float(comp[(comp["technology"] == "h2-sofc") & (comp["parameter"] == "efficiency_2")]["value"].iloc[0])
lifetime = {k: float(td[(td["technology"] == key) & (td["parameter"] == "lifetime")]["value"].iloc[0])
            for key, _, _, k in OPTIONS}

fig, ax = plt.subplots(figsize=(7.2, 3.9), layout="constrained")
ax.set_xscale("log"); ax.set_yscale("log")
for axis in (ax.xaxis, ax.yaxis):
    axis.set_major_locator(LogLocator(base=10, subs=(1.0,), numticks=14))
    axis.set_minor_locator(LogLocator(base=10, subs=(2.0, 5.0), numticks=14))
    axis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:g}" if v < 1 else f"{v:,.0f}"))
    axis.set_minor_formatter(NullFormatter())
ax.set_xlim(0.1, 1000); ax.set_ylim(1, 300)
grid(ax, log=True, axis="both")
RED, BLUE = "#c0392b", "#2c5f8a"
for kind, colour in (("tank", RED), ("cavern", BLUE)):    # two viable options, neither is "the" default
    r = rows[kind]
    ax.axhline(r["usd"], color=colour, linestyle=(0, (5, 3)), linewidth=1.2, zorder=3)
    ax.text(0.985, r["usd"], f"{r['label']}: {r['usd']:,.3g} {BASE}/kWh$_{{H_2}}$ "
            f"(= {r['usd'] / eff:,.0f} per kWh of electricity out)",
            transform=matplotlib.transforms.blended_transform_factory(ax.transAxes, ax.transData),
            color=colour, fontsize=8, ha="right", va="bottom", zorder=4,
            bbox=dict(facecolor="white", edgecolor="none", pad=1.5))
ax.set_xlabel("Cumulative installed capacity [GWh$_{H_2}$]")
ax.set_ylabel(f"Energy capacity cost [{BASE}/kWh$_{{H_2}}$]")
_save(fig, [o for o in OUTPUTS if o.suffix != ".tex"], CFG["plotting"]["dpi"])

tex = [o for o in OUTPUTS if o.suffix == ".tex"][0]
tank, cav = rows["tank"], rows["cavern"]
tex.write_text(
    "% generated by plot_h2_storage.py\n"
    f"\\href{{{DEA_URL}}}{{[1]}}~Danish Energy Agency, Technology Data for Energy Storage, sheet {tank['sheet']} "
    f"(tanks incl. compressor, {tank['eur']:.0f} EUR{tank['year']}/kWh, {lifetime['tank']:.0f} a)\\quad\n"
    f"\\href{{{DEA_URL}}}{{[2]}}~same catalogue, sheet {cav['sheet']} (caverns, {cav['eur']:.1f} EUR{cav['year']}/kWh, "
    f"{lifetime['cavern']:.0f} a)\\quad\n"
    f"\\href{{{TD_URL}}}{{[3]}}~via PyPSA/technology-data {CFG['technology_data']['tag']}\n")
print("wrote", tex, {k: round(v["usd"], 2) for k, v in rows.items()}, "eff", eff)
