# SPDX-License-Identifier: CC0-1.0
"""
Build models/pypsa-earth/config.yaml for one run.sh stage and print its Snakemake target.

    pixi run python ../../config-pypsa-earth/merge_config.py <kind> <stage> <out.yaml>

kind = prenetwork : config.<stage>.yaml copied as is; target networks/<stage>/elec_s{simpl}_{clusters}_ec_l{ll}_{opts}.nc
kind = overlay    : stage <R>-<scen> = config.<R>.yaml deep-merged with overlay.<scen>.yaml, run.name = stage,
                    catalyst.base_run = R; target results/<stage>/plots/validation_elec_s..._{opts}.png
kind = dashboard  : stage <R> = config.<R>.yaml + the validation custom rule; target results/catalyst/validation_<R>.png
Rest-of-world groups (catalyst.single_node in config.<G>.yaml, written by scripts/select_countries.py): catalyst.extra_opts
(ATKc) is prepended to every overlay opt (3h -> ATKc-3h, Co2L0-3h -> ATKc-Co2L0-3h), and the overlay target is the solved
network results/<stage>/networks/<stem>.nc (no per-network validation page; plot_world.py draws all countries at once).
The first element of every scenario list is used for the target (run.sh runs one scenario per stage).
"""
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
SMK = "../../config-pypsa-earth/validation.smk"  # relative to the fork root, see custom_rules in the overlays


def deep_merge(base, over):
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            deep_merge(base[k], v)
        else:
            base[k] = v
    return base


def load(name):
    with open(os.path.join(HERE, name)) as f:
        return yaml.safe_load(f) or {}


def stage_config(kind, stage):
    """Merged config dict of one stage."""
    if kind == "overlay":
        base_run, scen = stage.rsplit("-", 1)
        cfg = deep_merge(load(f"config.{base_run}.yaml"), load(f"overlay.{scen}.yaml"))
        cfg.setdefault("run", {})["name"] = stage
        cat = cfg.setdefault("catalyst", {})
        cat.update(base_run=base_run, scenario=scen)
        if cat.get("extra_opts"):
            cfg["scenario"]["opts"] = [f"{cat['extra_opts']}-{o}" for o in cfg["scenario"]["opts"]]
    else:
        cfg = load(f"config.{stage}.yaml")
        if kind == "dashboard":
            cfg["custom_rules"] = sorted(set(cfg.get("custom_rules", []) or []) | {SMK})
    return cfg


def network_stem(cfg):
    sc = cfg["scenario"]
    first = {k: str(sc[k][0]) for k in ("simpl", "clusters", "ll", "opts")}
    return "elec_s{simpl}_{clusters}_ec_l{ll}_{opts}".format(**first)


def solved_network(region, scen):
    """Path (relative to the fork root) of the solved screening network <region>-<scen>."""
    stage = f"{region}-{scen}"
    return f"results/{stage}/networks/{network_stem(stage_config('overlay', stage))}.nc"


def target_of(kind, stage, cfg):
    stem = network_stem(cfg)
    if kind == "prenetwork":
        return f"networks/{stage}/{stem}.nc"
    if kind == "overlay" and cfg["catalyst"].get("single_node"):
        return f"results/{stage}/networks/{stem}.nc"
    if kind == "overlay":
        return f"results/{stage}/plots/validation_{stem}.png"
    return f"results/catalyst/validation_{stage}.png"


if __name__ == "__main__":
    kind, stage, out = sys.argv[1:4]
    cfg = stage_config(kind, stage)
    with open(out, "w") as f:
        f.write(f"# generated by config-pypsa-earth/merge_config.py for stage '{stage}' ({kind}); do not edit\n")
        yaml.safe_dump(cfg, f, sort_keys=False)
    print(target_of(kind, stage, cfg))
