# SPDX-License-Identifier: CC0-1.0
"""
Build models/pypsa-earth/config.yaml for one run.sh stage and print its Snakemake target.

    pixi run python ../../config-pypsa-earth/merge_config.py <kind> <stage> <out.yaml>

kind = prenetwork : config.<stage>.yaml copied as is; target networks/<stage>/elec_s{simpl}_{clusters}_ec_l{ll}_{opts}.nc
kind = overlay    : stage <R>-<scen> = config.<R>.yaml deep-merged with overlay.<scen>.yaml, run.name = stage,
                    catalyst.base_run = R; target results/<stage>/plots/validation_elec_s..._{opts}.png
kind = dashboard  : stage <R> = config.<R>.yaml + the validation custom rule; target results/catalyst/validation_<R>.png
The first element of every scenario list is used for the target (run.sh runs one scenario per stage).
"""
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
SMK = "../../config-pypsa-earth/validation.smk"  # relative to the fork root, see custom_rules in the overlays


def deep_merge(base, over):
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            deep_merge(base[k], v)
        else:
            base[k] = v
    return base


def load(name):
    with open(os.path.join(HERE, name)) as f:
        return yaml.safe_load(f) or {}


kind, stage, out = sys.argv[1:4]
if kind == "overlay":
    base_run, scen = stage.rsplit("-", 1)
    cfg = deep_merge(load(f"config.{base_run}.yaml"), load(f"overlay.{scen}.yaml"))
    cfg.setdefault("run", {})["name"] = stage
    cfg["catalyst"] = {"base_run": base_run, "scenario": scen}
else:
    cfg = load(f"config.{stage}.yaml")
    if kind == "dashboard":
        cfg["custom_rules"] = sorted(set(cfg.get("custom_rules", []) or []) | {SMK})

sc = cfg["scenario"]
first = {k: str(sc[k][0]) for k in ("simpl", "clusters", "ll", "opts")}
stem = "elec_s{simpl}_{clusters}_ec_l{ll}_{opts}".format(**first)
if kind == "prenetwork":
    target = f"networks/{stage}/{stem}.nc"
elif kind == "overlay":
    target = f"results/{stage}/plots/validation_{stem}.png"
else:
    target = f"results/catalyst/validation_{stage}.png"

with open(out, "w") as f:
    f.write(f"# generated by config-pypsa-earth/merge_config.py for stage '{stage}' ({kind}); do not edit\n")
    yaml.safe_dump(cfg, f, sort_keys=False)
print(target)
