"""Build data/regions.js: sub-national grid regions that replace their country on the land grid map.

Mirrors the splits in misc-quarter1/country-classification/split_us.py, split_au.py and split_my.py:
  USA -> USE (Eastern Interconnection incl. ERCOT/Texas), USW (Western: the 11 WECC states),
         USAK / USHI (Alaska, Hawaii: outside every modelled grid, no data, no outline)
  AUS -> AUN (NEM + NT + off-grid remainder), AUW (SWIS ~ Western Australia)
  MYS -> MYW (Peninsular), MYE (Borneo: Sabah, Sarawak, Labuan), split at 106°E
and the merge in merge_nwe.py:
  IRL + GBR + FRA + BEL + NLD + LUX + DEU + DNK + CHE + AUT + CZE + POL -> NWE (North-West Europe,
         the countries of config-pypsa-earth/config.NWE.yaml, one region; the French overseas
         departments are clipped away and the twelve parents are not drawn)

Output: window.REGIONS_GEO = GeoJSON FeatureCollection, each feature with properties
{ id, name, replaces } where `replaces` is the M49 id of the country the region belongs to (a list
of ids for a merged region). The page drops the replaced country geometries and rasterises the
regions in their place, so cells, colours, outlines and CSV exports resolve to the region ids used
in country_features.csv.

Run from misc-quarter1/country-classification: ../../models/priam-myopic/.pixi/envs/default/bin/python build_regions.py
"""
import json
import os

import geopandas as gpd
from shapely.geometry import box
from shapely.ops import unary_union

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, 'data')
OUT = os.path.join(HERE, 'land-grid-map', 'data', 'regions.js')   # the front-end repo

NWE = {'IRL': '372', 'GBR': '826', 'FRA': '250', 'BEL': '056', 'NLD': '528', 'LUX': '442',
       'DEU': '276', 'DNK': '208', 'CHE': '756', 'AUT': '040', 'CZE': '203',
       'POL': '616'}   # as in merge_nwe.py, with the M49 ids the map keys countries by
NWE_BOX = box(-15, 41, 25, 62)   # Ireland to eastern Poland, Corsica to Shetland; drops overseas France
WEST = {'WA', 'OR', 'CA', 'NV', 'ID', 'UT', 'AZ', 'NM', 'CO', 'WY', 'MT'}
ISOLATED = {'AK': 'USAK', 'HI': 'USHI'}   # not part of any modelled grid: own region without data


def us_region(postal):
    if postal in ISOLATED:
        return ISOLATED[postal]
    return 'USW' if postal in WEST else 'USE'


def main():
    adm1 = gpd.read_file(os.path.join(DATA, 'ne_50m_admin_1_states_provinces'))
    adm0 = gpd.read_file(os.path.join(DATA, 'ne_50m_admin_0_countries'))
    feats = []

    def add(rid, name, replaces, geom):
        geom = geom.simplify(0.002, preserve_topology=True)
        feats.append({'type': 'Feature', 'id': rid,
                      'properties': {'id': rid, 'name': name, 'replaces': replaces},
                      'geometry': json.loads(gpd.GeoSeries([geom]).to_json())['features'][0]['geometry']})

    us = adm1[adm1['adm0_a3'] == 'USA'].copy()
    us['region'] = us['postal'].map(us_region)
    names = {'USE': 'United States (East)', 'USW': 'United States (West)', 'USAK': 'Alaska', 'USHI': 'Hawaii'}
    for rid, grp in us.groupby('region'):
        add(rid, names[rid], '840', unary_union(grp.geometry.values))

    au = adm1[adm1['adm0_a3'] == 'AUS'].copy()
    au['region'] = (au['postal'] == 'WA').map({True: 'AUW', False: 'AUN'})
    names = {'AUN': 'Australia (NEM)', 'AUW': 'Australia (SWIS)'}
    for rid, grp in au.groupby('region'):
        add(rid, names[rid], '036', unary_union(grp.geometry.values))

    col = 'ADM0_A3' if 'ADM0_A3' in adm0.columns else 'adm0_a3'
    my = adm0[adm0[col] == 'MYS'].geometry.iloc[0]
    west = my.intersection(box(90, -5, 106, 15))
    east = my.intersection(box(106, -5, 130, 15))
    add('MYW', 'Malaysia (Peninsular)', '458', west)
    add('MYE', 'Malaysia (Borneo)', '458', east)

    nwe = unary_union(adm0[adm0[col].isin(NWE)].geometry.values).intersection(NWE_BOX)
    add('NWE', 'North-West Europe', list(NWE.values()), nwe)

    fc = {'type': 'FeatureCollection', 'features': feats}
    txt = json.dumps(fc, separators=(',', ':'))
    # trim coordinate precision to 4 decimals (~10 m) to keep the file small
    import re
    txt = re.sub(r'(-?\d+\.\d{4})\d+', r'\1', txt)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// GENERATED by build_regions.py — grid regions replacing USA, AUS, MYS and eight North-West European countries on the map.\n')
        f.write('window.REGIONS_GEO = ' + txt + ';\n')
    print(OUT, len(feats), 'regions,', os.path.getsize(OUT) // 1024, 'KB')
    for f_ in feats:
        print(' ', f_['id'], f_['properties']['name'], 'replaces', f_['properties']['replaces'])


if __name__ == '__main__':
    main()
