"""Build data/population.js for the land grid map.

Source: GPW v4 (rev 11) population count 2020, 30 arc-second, served as a Cloud
Optimized GeoTIFF by the Stanford Natural Capital Alliance. Only the internal
overview at factor 8 (4 arc-minute, 5400 x 2700) is fetched via HTTP range
requests, so the download is a few tens of MB rather than the 577 MB full file.

Output: an equirectangular grid of population counts per 4' cell, log-encoded
as 16 bits split across the R and G channels of a PNG, embedded as a base64
data URI in data/population.js so the page can read it from file:// without a
tainted canvas.

    count = 10 ** (q / 65535 * LOG_MAX) - 1,   q = R * 256 + G

Run with an environment that has rasterio and Pillow:
    ~/micromamba/envs/pypsa-demand/bin/python prepare_population.py
"""
import base64
import io
import os
import sys

import numpy as np

URL = ('https://data.naturalcapitalalliance.stanford.edu/download/global/'
       'ciesin-nasa-gpw-grdi/ciesen_nasa_gpw_v4_population_count_2020.tif')
FACTOR = 8          # overview level: 30" * 8 = 4 arc-minutes
LOG_MAX = 7.0       # log10(count + 1) upper bound for the 16-bit encoding

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, 'land-grid-map', 'data')   # the front-end repo
CACHE = os.path.join(HERE, 'data', 'gpw_v4_2020_4min.npy')   # 58 MB array cache, stays with the pipeline data


def fetch():
    import rasterio
    from rasterio.enums import Resampling
    os.environ.setdefault('GDAL_DISABLE_READDIR_ON_OPEN', 'EMPTY_DIR')
    os.environ.setdefault('GDAL_HTTP_TIMEOUT', '120')
    with rasterio.open('/vsicurl/' + URL) as src:
        assert FACTOR in src.overviews(1), src.overviews(1)
        H, W = src.height // FACTOR, src.width // FACTOR
        a = src.read(1, out_shape=(H, W), resampling=Resampling.average)
        a = np.where(np.isfinite(a) & (a != src.nodata) & (a >= 0), a, 0)
        return (a * FACTOR * FACTOR).astype('float32')   # average -> sum per coarse cell


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    if os.path.exists(CACHE):
        a = np.load(CACHE)
    else:
        a = fetch()
        np.save(CACHE, a)
    H, W = a.shape
    print(f'grid {W}x{H}, total {a.sum():.4g}, max cell {a.max():.4g}')

    q = np.clip(np.log10(a + 1) / LOG_MAX, 0, 1)
    q = np.round(q * 65535).astype('uint16')
    rgb = np.zeros((H, W, 3), dtype='uint8')
    rgb[..., 0] = q >> 8
    rgb[..., 1] = q & 255

    from PIL import Image
    buf = io.BytesIO()
    Image.fromarray(rgb).save(buf, format='PNG', optimize=True)
    png = buf.getvalue()
    b64 = base64.b64encode(png).decode('ascii')

    js = (
        '// GENERATED by prepare_population.py — GPW v4 rev11 population count 2020,\n'
        '// 4 arc-minute equirectangular grid (%d x %d), lon -180..180, lat 90..-90.\n'
        '// count = 10 ** (q / 65535 * %g) - 1, q = R*256 + G.\n'
        'window.POPULATION_GRID = { width: %d, height: %d, logMax: %g,\n'
        '  source: "CIESIN/NASA SEDAC GPW v4.11, 2020",\n'
        '  png: "data:image/png;base64,%s" };\n'
    ) % (W, H, LOG_MAX, W, H, LOG_MAX, b64)
    out = os.path.join(OUT_DIR, 'population.js')
    with open(out, 'w') as f:
        f.write(js)
    print(f'png {len(png)/1e6:.2f} MB, js {len(js)/1e6:.2f} MB -> {out}')


if __name__ == '__main__':
    sys.exit(main())
